### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by medrockstar** [gadjetboi/WhatsNearby#1]
Hi,

Tks for your code.

When I install the it's freezing in loading and not show's anything.

Can show how you get information of stores ans deals ?

Tks,

**Comment by gadjetboi** [comment]
Hi,

I’m using Yelp API for business nearby and Groupon API for groupon deals.

To setup please see below:

**Yelp API**
1.) You need to signup in yelp to get consumer key and oauth token to have an access to yelp api. - https://www.yelp.com/signup

2.) In “WhatsNearby/WhatsNearby/www/js/services.js” update search method in YelpApi factory and fill-up the “oauth_consumer_key”, “oauth_token”, “consumerSecret”, “tokenSecret” properties with your credentials.

**Groupon Api**
1.) Register to groupon partner to get the token and have an access to groupon deals api. - https://partner.groupon.com/login

2.) In “WhatsNearby/WhatsNearby/www/js/services.js” update search method in GrouponApi factory and fill-up the “tsToken” property with your token.

Good luck!
